<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5a6tGAX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5a6tGAX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5a6tGAX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5a6tGAX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5a6tGAX\App_KernelDevDebugContainer([
    'container.build_hash' => '5a6tGAX',
    'container.build_id' => '6cea80aa',
    'container.build_time' => 1696501997,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5a6tGAX');
