<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUVLpbGQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUVLpbGQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUVLpbGQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUVLpbGQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUVLpbGQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'UVLpbGQ',
    'container.build_id' => '7e9cca0d',
    'container.build_time' => 1697458011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUVLpbGQ');
